<?php

$arr = [
    'Home',
    'About Us',
    'Services',
    'Blog',
    'FAQ',
    'Contact',
    'API DOCS',
    'Login',
    'Sign up',
    'Dashboard',
    'Logout',
    'Copyright',
    'All Rights Reserved',
    'Email Or Username',
    'Password',
    'Confirm Password',
    'Current Password',
    'Forgot Your Password?',
    'REGISTER',
    'First Name',
    'Last Name',
    'Username',
    'Address',
    'Email Address',
    'Phone Number',
    'Your Phone Number',
    'Already have account?',
    'Reset Password',
    'Don\'t have an account?',
    'Send Password Reset Link',
    'New Password',
    'Code',
    'Submit',
    '403 Forbidden',
    'You don’t have permission to access ‘/’ on this server.',
    'Back To Home',
    'Sorry page was not found!',
    'We\'re sorry, the page you requested could not be found. Please go back to the homepage or contact us at',
    'Method not allowed',
    'opps!',
    'Session has expired',
    'We Accept',
    'Search for Services',
    'All Category',
    'Search',
    'ID',
    'Name',
    'Rate Per 1k',
    'Min / Max Order',
    'Description',
    'Close',
    'Order Now',
    'API DETAILS',
    'API URL',
    'API KEY',
    'HTTP METHOD',
    'RESPONSE FORMAT',
    'PLACE NEW ORDER',
    'key',
    'Action',
    'service',
    'link',
    'quantity',
    '(optional)',
    'interval',
    'STATUS ORDER',
    'MULTIPLE STATUS ORDER',
    'SERVICE LIST',
    'USER BALANCE',
    'Message',
    'Enter Message',
    'Send Message',
    'Order',
    'New Order',
    'All Order',
    'Mass Order',
    'Add Fund',
    'Fund History',
    'Transactions',
    'Transaction',
    'My Profile',
    'API Setting',
    'Open Ticket',
    'Show Ticket',
    'No Data found',
    'Your Balance',
    'Total Transaction',
    'Total Deposit',
    'Total Tickets',
    'Total Orders',
    'Processing Orders',
    'Pending Orders',
    'Completed Orders',
    'Transaction ID',
    'Amount',
    'Remarks',
    'Time',
    'Email Verification',
    'Submit',
    'Quantity',
    'Drip-feed',
    'Runs',
    'Interval (in minutes)',
    'Total Quantity',
    'Price',
    'Yes, i have confirmed the order!',
    'Service name',
    'Minimum Amount',
    'Maximum Amount',
    'Each Order On New Line',
    'Save Changes',
    'All Status',
    'Awaiting',
    'Pending',
    'Processing',
    'In Progress',
    'Completed',
    'Partial',
    'Cancelled',
    'Refunded',
    'Order ID',
    'Order Details',
    'Start Counter',
    'Remains',
    'Order AT',
    'Status',
    'Note',
    'Profile Settings',
    'Update User',
    'Update Password',
    'Search Service',
    'Subject',
    'Image Upload',
    'Upload',
    'Last Reply',
    'Reply',
    'Open',
    'Answered',
    'Customer Reply',
    'Closed',
    'Upload File',
    'Confirm',
    'Are you want to close ticket?',
    'Type Here',
    'All Payment',
    'Complete Payment',
    'Pending Payment',
    'Cancel Payment',
    'Gateway',
    'Charge',
];

return $arr;
